### ISSUE TITLE
Add option to skip conform_config_file

### ISSUE THREAD

**Issue by snsmac** [sakaki-/buildkernel#26]
This would be useful for some custom kernel configs.
I will probably write a PR for this

**Comment by sakaki-** [comment]
OK, if you push a PR I will review and merge it. See e.g. PR #25 for an example of such a change (including manpage change, version bump etc.)
Thanks, sakaki

**Comment by sakaki-** [comment]
31 Oct 2020: sadly, due to legal obligations arising from a recent change in my 'real world' job, I must announce I am **standing down as maintainer of this project with immediate effect**. For the meantime, I will leave the repo up (for historical interest, and it may be of use to others); however, I plan no further updates, nor will I be accepting / actioning further pull requests or bug reports from this point. Email requests for support will also have to be politely declined, so, **please treat this as an effective EOL notice**.<br><br>For further details, please see my post [here](https://forums.gentoo.org/viewtopic-p-8522963.html#8522963).<br><br>With sincere apologies, sakaki ><

**Comment by jorickert** [comment]
I wish you all good for your future, thanks for your great work :)
